FROM node:18-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

EXPOSE 5173

# 👇 On remplace "npm run dev" par l’équivalent explicite
CMD ["npx", "vite", "--host", "0.0.0.0", "--port", "5173"]
